kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    stringData:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    kind: Secret
    metadata:
      name: devhub-api-github
      labels:
        app: devhub-api
        rootComponent: devhub-api
parameters:
  - name: GITHUB_TOKEN
    required: true 
    displayName: Github Token