kind: Template
apiVersion: v1
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: devhub-dev-${SUFFIX}
        component: ${NAME}-${SUFFIX}
        rootComponent: ${NAME}
      name: ${NAME}
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    spec:
      replicas: 3
      selector:
        app: devhub-dev-${SUFFIX}
        component: ${NAME}-${SUFFIX}
        rootComponent: ${NAME}
      
        deploymentconfig: devhub-app-web
      strategy:
        resources: {}
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            app: devhub-api-${SUFFIX}
            component: ${NAME}-${SUFFIX}
            rootComponent: ${NAME}
          
            deploymentconfig: devhub-app-web
        spec:
          containers:
            - image: '${NAME}:${VERSION}'
              name: ${NAME}
              env:
                - name: PORT 
                  value: "3000"
                - name: HOST 
                  value: ${SERVER_HOST}
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: GITHUB_TOKEN
                      name: ${NAME}-github
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /v1/checks/ehlo
                  port: 3000
                  scheme: HTTP
                initialDelaySeconds: 4
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 50
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: '${NAME}:${SUFFIX}'
          type: ImageChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: devhub-dev-${SUFFIX}
        component: ${NAME}-${SUFFIX}
        rootComponent: ${NAME}
      
      name: ${NAME}-${SUFFIX}
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          # I wanted to parametrize target port but template params do not allow integer values atm
          targetPort: 3000
      selector:
        app: devhub-api-${SUFFIX}
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: devhub-dev-${SUFFIX}
        component: ${NAME}-${SUFFIX}
        rootComponent: ${NAME}
      name: ${NAME}-${SUFFIX}
  - apiVersion: route.openshift.io/v1
    kind: Route
    spec:
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${NAME}-${SUFFIX}
        weight: 100
      wildcardPolicy: None
    metadata:
      annotations:
        openshift.io/host.generated: 'true'
      labels:
        app: devhub-dev-${SUFFIX}
        component: ${NAME}-${SUFFIX}
        rootComponent: ${NAME}
      name: ${NAME}-${SUFFIX}
  
parameters:
  - name: SERVER_HOST
    value: "0.0.0.0"
    description: the host the server runs on 
    displayName: Server Host
  - name: NAME
    value: devhub-api
    description: the component name
    displayName: Name
  - name: SUFFIX
    value: dev
    description: the suffix applied to app instances 
    displayName: Suffix
  - name: VERSION
    value: "1.0.0"
    description: the version applied to image tag 
    displayName: Version
  - description: The CPU Request for the deployment config
    displayName: CPU Request 
    name: CPU_REQUEST
    required: false
    value: 100m
  - description: The CPU Limit for the deployment config
    displayName: CPU Limit 
    name: CPU_LIMIT
    required: false
    value: 150m
  - description: The Memory Request for the deployment config
    displayName: Memory Request 
    name: MEMORY_REQUEST
    required: false
    value: 50Mi
  - description: The Memory Limit for the deployment config
    displayName: Memory Limit 
    name: MEMORY_LIMIT
    required: false
    value: 75Mi